### PR TITLE
Corrected time of sunrise again

### PR DESCRIPTION
**Pull request by Wampa842**
The time of sunrise was changed again, this time back by 2:30. I've changed `start_time` to a timestamp that coincides with the reset of the bounties.

### CODE REVIEW

**Comment by lyneca** [comment]
Was it changed, or do you think my algorithm is wrong?

In any case, I should probably pull the data from a more reputable source (like warframestat.us) every time the page loads.

**Comment by Wampa842** [comment]
The algorithm is solid, the day is still a 100+50 minute cycle - I'm pretty sure the clock is reset every time an update is released.

If you want to pull the data from an official source, you should probably do it from the official world state file at http://content.warframe.com/dynamic/worldState.php  
It contains the activation and expiration timestamps of the Cetus bounties in the SyndicateMissions array where the "tag" attribute is "CetusSyndicate".

**Comment by lyneca** [comment]
Yeah that's probably a better idea. Thanks!

**Comment by Wampa842** [comment]
Here, I've done some coding. https://gist.github.com/Wampa842/d14620cdc699a8c01c9c2662c217ea4b

It's a bit messy, but I've tested it and it works. I'll try to integrate it into the website once I've had some sleep.

**Comment by lyneca** [comment]
You absolute legend.

**Comment by lyneca** [comment]
What is the activation time for Cetus? I'm integrating the code, but it's about 7 minutes off.

**Comment by lyneca** [comment]
Nevermind, got it

**Comment by Wampa842** [comment]
Mine's six minutes off - what was the issue?

**Comment by lyneca** [comment]
Should be live now, just pushed. Lmao, it's because I was literally adding 7 minutes to the time.

**Comment by LilithTundrus** [comment]
I'm still getting around a minute off of you, any ideas? [Gist](https://gist.github.com/LilithTundrus/afdbf9ccf4ea7ee161491403a4561c66)

**Pull request merged**
